### ISSUE TITLE
Suddenly blank

### ISSUE THREAD

**Issue by twister5800** [harriedegroot/nl.hdg.battery#3]
Hi,

Running Homey pro 2 v2.1.1 firmware.

No it's just blank = no battery devices.

Your temp app works fine :-)

Regards Martin

**Comment by harriedegroot** [comment]
It's a known bug in Homey. Multiple apps are hit by this issue. Athom already resolved it and the next release of Homey will contain the fix.
For a workaround see: https://community.athom.com/t/app-group-2-3-1-stable/3168/163

**Comment by twister5800** [comment]
Thanks. I did not Update from V1 though. Reboot helped. Thanks ;-)
