### ISSUE TITLE
Ikea remotes does not show in app

### ISSUE THREAD

**Issue by snurre66** [harriedegroot/nl.hdg.battery#9]
Recognizes many of my devices, but not my ikea remotes...

**Comment by harriedegroot** [comment]
Contact the developer of the IKEA app.

**Comment by snurre66** [comment]
Ok. My mistake...
For my curiosity only: Is there some correct way to program the battery measure capability in the apps? Or something like that...

**Comment by harriedegroot** [comment]
You're correct. The app must provide the measure_battery capability for the remote.
